server:
  port: 8080
spring:
  data:
    redis:
      host: localhost
      port: 6379
      client-type: lettuce
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:posgresql://localhost:5432/postgres
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
    defer-datasource-initialization: true
  sql:
    init:
      schema-locations: classpath:db/postgres/ddl.sql
      mode: always
